/**
 * Production-Grade Client-Side PDF Export Engine for KDP Studio Tools
 * Generates razor-sharp 300 DPI vector PDFs for:
 * - Executive Royalty & Print Cost Reports
 * - Back-of-Book Lead Magnet QR Pages (with Amazon KDP Gutter Margins)
 * - Complete Multi-Page Maze Puzzle Books + Solution Keys
 * - Complete Multi-Page Cryptogram Books + Solution Keys
 * - Reverse ASIN Competitor Dossiers
 */

import jsPDF from 'jspdf';
import { CalculationResult, CalculationInput, KDP_MARKETPLACES } from './kdpCalculatorEngine';
import { AsinCompetitorData } from './asinSpyEngine';
import { generateMaze, MazeDifficulty, MazeShape } from './puzzles/mazeEngine';
import { generateCryptogram, CRYPTOGRAM_QUOTE_BANKS } from './puzzles/cryptogramEngine';
import { generateSudoku, SudokuDifficulty } from './puzzles/sudokuEngine';
import { generateCrossword, CROSSWORD_THEMES } from './puzzles/crosswordEngine';
import { ChildrensBookProject } from './studios/childrensBookEngine';
import { CookbookProject } from './studios/cookbookEngine';
import { PlannerConfig } from './studios/plannerEngine';
import { NonFictionProject } from './studios/nonfictionEngine';
import { FictionProject } from './studios/fictionEngine';
import { WorkbookProject } from './studios/workbookEngine';

// Standard KDP trim dimensions in inches
export const TRIM_SIZES_INCHES: Record<string, { width: number; height: number }> = {
  '6x9': { width: 6.0, height: 9.0 },
  '5.5x8.5': { width: 5.5, height: 8.5 },
  '8.5x11': { width: 8.5, height: 11.0 },
  '8.5x8.5': { width: 8.5, height: 8.5 },
  '5x8': { width: 5.0, height: 8.0 },
};

/**
 * 1. Exports an Executive KDP Royalty & Pricing Sheet PDF
 */
export function exportRoyaltyReportPdf(calc: CalculationResult, input: CalculationInput): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [8.5, 11.0],
    compress: true,
  });

  const marginX = 0.75;
  const marginY = 0.75;
  const contentW = 8.5 - marginX * 2;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 8.5, 1.6, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Amazon KDP Royalty & Print Cost Report', marginX, 0.75);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(192, 132, 252); // purple-300
  doc.text(`Generated by KDP Studio • ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, marginX, 1.05);

  // Specifications Box
  let y = 2.0;
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(marginX, y, contentW, 1.4, 0.1, 0.1, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Book Parameters', marginX + 0.25, y + 0.35);

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);

  doc.text(`• Marketplace: ${calc.marketplace.name}`, marginX + 0.25, y + 0.65);
  doc.text(`• Format: ${input.binding.toUpperCase()} (${input.trimCategory === 'large' ? 'Large Trim' : 'Standard Trim'})`, marginX + 0.25, y + 0.9);
  doc.text(`• Interior Ink: ${input.inkType.replace(/_/g, ' ').toUpperCase()}`, marginX + 0.25, y + 1.15);

  doc.text(`• Page Count: ${input.pageCount} Pages`, marginX + 3.8, y + 0.65);
  doc.text(`• List Price: ${calc.marketplace.currencySymbol}${input.listPrice.toFixed(2)}`, marginX + 3.8, y + 0.9);
  doc.text(`• Distribution: ${input.expandedDistribution ? 'Expanded (40%)' : 'Standard (60%)'}`, marginX + 3.8, y + 1.15);

  // Financial Breakdown Matrix
  y = 3.7;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Profit & Cost Matrix', marginX, y);

  y += 0.25;
  const metrics = [
    { label: 'Retail List Price', val: `${calc.marketplace.currencySymbol}${input.listPrice.toFixed(2)}`, color: [15, 23, 42] },
    { label: 'Amazon Printing Cost', val: `- ${calc.marketplace.currencySymbol}${calc.printingCost.toFixed(2)}`, color: [225, 29, 72] },
    { label: 'Amazon Marketplace Share', val: `- ${calc.marketplace.currencySymbol}${calc.amazonCut.toFixed(2)}`, color: [217, 119, 6] },
    { label: 'Net Author Royalty per Sale', val: `${calc.marketplace.currencySymbol}${calc.royaltyPerSale.toFixed(2)}`, color: [16, 185, 129] },
    { label: 'Net Profit Margin Percentage', val: `${calc.profitMarginPercent}%`, color: [147, 51, 234] },
    { label: 'Minimum Break-Even Retail Price', val: `${calc.marketplace.currencySymbol}${calc.minListPrice.toFixed(2)}`, color: [71, 85, 105] },
    { label: 'Sales for $1,000 Net Royalty', val: `${calc.breakEvenCopiesFor1000Revenue} copies`, color: [15, 23, 42] },
  ];

  metrics.forEach((m, idx) => {
    const rowY = y + idx * 0.42;
    doc.setFillColor(idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 252);
    doc.rect(marginX, rowY, contentW, 0.42, 'F');
    doc.setDrawColor(241, 245, 249);
    doc.line(marginX, rowY + 0.42, marginX + contentW, rowY + 0.42);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(m.label, marginX + 0.2, rowY + 0.27);

    doc.setTextColor(m.color[0], m.color[1], m.color[2]);
    doc.text(m.val, marginX + contentW - 0.2, rowY + 0.27, { align: 'right' });
  });

  // Global Marketplaces Comparison Table
  y = 7.3;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Global Amazon Marketplaces Side-by-Side', marginX, y);

  y += 0.3;
  const majorMps = [
    { code: 'US', name: 'United States (USD)', price: '$9.99' },
    { code: 'UK', name: 'United Kingdom (GBP)', price: '£8.99' },
    { code: 'DE', name: 'Eurozone (EUR)', price: '€9.99' },
    { code: 'CA', name: 'Canada (CAD)', price: 'CA$13.99' },
    { code: 'AU', name: 'Australia (AUD)', price: 'A$16.99' },
    { code: 'IN', name: 'India (INR)', price: '₹499' }
  ];

  doc.setFillColor(15, 23, 42);
  doc.rect(marginX, y, contentW, 0.35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Marketplace', marginX + 0.2, y + 0.23);
  doc.text('Est. Print Cost', marginX + 2.5, y + 0.23);
  doc.text('Est. Author Royalty', marginX + 4.5, y + 0.23);
  doc.text('Status', marginX + contentW - 0.2, y + 0.23, { align: 'right' });

  majorMps.forEach((m, idx) => {
    const rowY = y + 0.35 + idx * 0.35;
    doc.setFillColor(idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 252);
    doc.rect(marginX, rowY, contentW, 0.35, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text(m.name, marginX + 0.2, rowY + 0.23);
    doc.text(`Included`, marginX + 2.5, rowY + 0.23);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129);
    doc.text(`60% Amazon Standard`, marginX + 4.5, rowY + 0.23);
    doc.setTextColor(79, 70, 229);
    doc.text('Active', marginX + contentW - 0.2, rowY + 0.23, { align: 'right' });
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Amazon KDP Print rates and formulas are subject to official Amazon KDP updates. Generated via https://kdpstudio-aio.web.app', marginX, 10.4);

  doc.save(`kdp_royalty_report_${calc.marketplace.code}_${input.pageCount}p.pdf`);
}

/**
 * 2. Exports 300 DPI Back-of-Book Lead Magnet QR Page PDF
 */
export async function exportLeadMagnetPagePdf(
  targetUrl: string,
  headline: string,
  subheadline: string,
  ctaText: string,
  trimSize: string = '6x9'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['6x9'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  // Gutter margins (0.75" inside for Amazon spine safe zone, 0.5" outside)
  const marginL = 0.75;
  const marginR = 0.5;
  const marginT = 0.65;
  const contentW = dims.width - marginL - marginR;

  // Decorative Border
  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(0.015);
  doc.rect(marginL, marginT, contentW, dims.height - marginT * 2);

  // Inner thin border
  doc.setLineWidth(0.008);
  doc.rect(marginL + 0.05, marginT + 0.05, contentW - 0.1, dims.height - marginT * 2 - 0.1);

  // Top Flourish
  let y = marginT + 0.5;
  doc.setFont('times', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text('❦', marginL + contentW / 2, y, { align: 'center' });

  // Main Headline
  y += 0.45;
  doc.setFontSize(trimSize === '8.5x11' ? 22 : 16);
  doc.setFont('times', 'bold');
  const splitHeadline = doc.splitTextToSize(headline, contentW - 0.5);
  doc.text(splitHeadline, marginL + contentW / 2, y, { align: 'center' });

  // Subheadline / Offer
  y += splitHeadline.length * 0.28 + 0.15;
  doc.setFontSize(trimSize === '8.5x11' ? 12 : 9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const splitSub = doc.splitTextToSize(subheadline, contentW - 0.6);
  doc.text(splitSub, marginL + contentW / 2, y, { align: 'center' });

  // QR Code Generation
  y += splitSub.length * 0.22 + 0.3;
  const qrSize = trimSize === '8.5x11' ? 2.5 : 1.8;
  const qrX = marginL + (contentW - qrSize) / 2;

  try {
    // Fetch QR Code PNG raster data for clean embedding
    const qrPngUrl = `https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=${encodeURIComponent(targetUrl)}&format=png&color=000000`;
    const response = await fetch(qrPngUrl);
    const blob = await response.blob();
    const reader = new FileReader();

    const base64Data = await new Promise<string>((resolve) => {
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });

    // White background card behind QR code
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(qrX - 0.1, y - 0.1, qrSize + 0.2, qrSize + 0.2, 0.05, 0.05, 'FD');
    doc.addImage(base64Data, 'PNG', qrX, y, qrSize, qrSize);
  } catch (err) {
    // Fallback QR Box if offline
    doc.setFillColor(241, 245, 249);
    doc.rect(qrX, y, qrSize, qrSize, 'F');
    doc.setFontSize(10);
    doc.text('Scan Code Here', marginL + contentW / 2, y + qrSize / 2, { align: 'center' });
  }

  // URL text under QR
  y += qrSize + 0.25;
  doc.setFontSize(8);
  doc.setFont('courier', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(targetUrl, marginL + contentW / 2, y, { align: 'center' });

  // CTA Pill at bottom
  y += 0.35;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(ctaText, marginL + contentW / 2, y, { align: 'center' });

  doc.save(`kdp_lead_magnet_${trimSize}.pdf`);
}

/**
 * 3. Exports Complete Multi-Page Maze Puzzle Book PDF + 4-per-page Answer Keys
 */
export async function exportMazeBookPdf(
  batchCount: number = 20,
  difficulty: MazeDifficulty = 'medium',
  shape: MazeShape = 'rectangle',
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const marginB = 0.75;
  const contentW = dims.width - marginL - marginR;
  const contentH = dims.height - marginT - marginB;

  // 1. Cover / Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('THE ULTIMATE', dims.width / 2, dims.height / 2 - 1.2, { align: 'center' });
  doc.setFontSize(36);
  doc.text('MAZE BOOK', dims.width / 2, dims.height / 2 - 0.5, { align: 'center' });
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${batchCount} High-Resolution Puzzles with Complete Solutions`, dims.width / 2, dims.height / 2 + 0.2, { align: 'center' });

  // Generate Mazes
  const mazes = Array.from({ length: batchCount }, () => generateMaze(22, 22, difficulty, shape));

  // 2. Puzzle Pages (1 maze per page)
  mazes.forEach((maze, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    // Page Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Puzzle #${idx + 1}`, marginL + contentW / 2, marginT + 0.3, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Difficulty: ${difficulty.toUpperCase()} • Find path from Start (Top-Left) to Finish (Bottom-Right)`, marginL + contentW / 2, marginT + 0.55, { align: 'center' });

    // Draw Vector Maze
    const mazeSize = Math.min(contentW, contentH - 1.5);
    const startX = marginL + (contentW - mazeSize) / 2;
    const startY = marginT + 0.85;
    const cellStep = mazeSize / maze.width;

    doc.setDrawColor(15, 23, 42);
    doc.setLineWidth(0.015);

    maze.cells.forEach((row, rY) => {
      row.forEach((cell, rX) => {
        const cx = startX + rX * cellStep;
        const cy = startY + rY * cellStep;

        if (cell.top) doc.line(cx, cy, cx + cellStep, cy);
        if (cell.right) doc.line(cx + cellStep, cy, cx + cellStep, cy + cellStep);
        if (cell.bottom) doc.line(cx, cy + cellStep, cx + cellStep, cy + cellStep);
        if (cell.left) doc.line(cx, cy, cx, cy + cellStep);
      });
    });

    // Page Number
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${idx + 1}`, dims.width / 2, dims.height - 0.4, { align: 'center' });
  });

  // 3. Solutions Section Header
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('SOLUTIONS', dims.width / 2, dims.height / 2, { align: 'center' });

  // 4. Solution Grids (4 solutions per page)
  const solutionsPerPage = 4;
  const numSolutionPages = Math.ceil(mazes.length / solutionsPerPage);

  for (let sPage = 0; sPage < numSolutionPages; sPage++) {
    doc.addPage([dims.width, dims.height], 'portrait');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(`Solutions — Part ${sPage + 1}`, dims.width / 2, marginT + 0.2, { align: 'center' });

    const pageMazes = mazes.slice(sPage * solutionsPerPage, (sPage + 1) * solutionsPerPage);
    const subW = (contentW - 0.4) / 2;
    const subH = (contentH - 1.0) / 2;

    pageMazes.forEach((maze, subIdx) => {
      const col = subIdx % 2;
      const row = Math.floor(subIdx / 2);
      const bx = marginL + col * (subW + 0.4);
      const by = marginT + 0.5 + row * (subH + 0.5);

      const realIdx = sPage * solutionsPerPage + subIdx + 1;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`Puzzle #${realIdx} Solution`, bx + subW / 2, by, { align: 'center' });

      // Draw mini maze with solution path
      const miniSize = Math.min(subW, subH - 0.3);
      const mStartX = bx + (subW - miniSize) / 2;
      const mStartY = by + 0.15;
      const mStep = miniSize / maze.width;

      doc.setDrawColor(148, 163, 184);
      doc.setLineWidth(0.008);

      maze.cells.forEach((row, rY) => {
        row.forEach((cell, rX) => {
          const cx = mStartX + rX * mStep;
          const cy = mStartY + rY * mStep;

          if (cell.top) doc.line(cx, cy, cx + mStep, cy);
          if (cell.right) doc.line(cx + mStep, cy, cx + mStep, cy + mStep);
          if (cell.bottom) doc.line(cx, cy + mStep, cx + mStep, cy + mStep);
          if (cell.left) doc.line(cx, cy, cx, cy + mStep);
        });
      });

      // Draw Solution Green Line
      doc.setDrawColor(16, 185, 129); // emerald-500
      doc.setLineWidth(0.015);
      for (let p = 0; p < maze.solutionPath.length - 1; p++) {
        const p1 = maze.solutionPath[p];
        const p2 = maze.solutionPath[p + 1];
        doc.line(
          mStartX + p1.x * mStep + mStep / 2,
          mStartY + p1.y * mStep + mStep / 2,
          mStartX + p2.x * mStep + mStep / 2,
          mStartY + p2.y * mStep + mStep / 2
        );
      }
    });
  }

  doc.save(`kdp_maze_book_${batchCount}_puzzles_${trimSize}.pdf`);
}

/**
 * 4. Exports Complete Multi-Page Cryptogram Book PDF + Answer Keys
 */
export async function exportCryptogramBookPdf(
  batchCount: number = 20,
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const contentW = dims.width - marginL - marginR;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('CRYPTOGRAMS', dims.width / 2, dims.height / 2 - 0.8, { align: 'center' });
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${batchCount} Inspiring Substitution Ciphers with Answer Keys`, dims.width / 2, dims.height / 2 - 0.2, { align: 'center' });

  const puzzles = Array.from({ length: batchCount }, (_, idx) => {
    const q = CRYPTOGRAM_QUOTE_BANKS[idx % CRYPTOGRAM_QUOTE_BANKS.length];
    return generateCryptogram(q.text, q.author, q.category, 2);
  });

  // Puzzles Pages (1 per page)
  puzzles.forEach((puzzle, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Cryptogram #${idx + 1}`, marginL + contentW / 2, marginT + 0.3, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Theme: ${puzzle.category} • Clues: ${puzzle.hints.map(h => `${h.cipher} = ${h.original}`).join('  |  ')}`, marginL + contentW / 2, marginT + 0.6, { align: 'center' });

    // Cipher Text Blocks
    let y = marginT + 1.2;
    doc.setFont('courier', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);

    const splitCipher = doc.splitTextToSize(puzzle.cipherText, contentW - 0.5);
    splitCipher.forEach((line: string) => {
      // Draw underline letter blanks above
      doc.setDrawColor(203, 213, 225);
      doc.setLineWidth(0.01);
      doc.text(line, marginL + 0.3, y);
      doc.line(marginL + 0.3, y - 0.2, marginL + contentW - 0.3, y - 0.2);
      y += 0.6;
    });

    // Author
    y += 0.3;
    doc.setFont('times', 'italic');
    doc.setFontSize(11);
    doc.setTextColor(71, 85, 105);
    doc.text(`— ${puzzle.authorOrSource}`, marginL + contentW - 0.5, y, { align: 'right' });

    // Letter Frequency Table
    y += 0.8;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 116, 139);
    doc.text('LETTER FREQUENCIES:', marginL + 0.3, y);
    y += 0.25;

    const freqEntries = Object.entries(puzzle.letterFrequencies).map(([l, c]) => `${l}:${c}`).join('  ');
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.text(doc.splitTextToSize(freqEntries, contentW - 0.6), marginL + 0.3, y);
  });

  // Solutions Section
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(24);
  doc.text('SOLUTIONS', dims.width / 2, marginT + 0.5, { align: 'center' });

  let solY = marginT + 1.0;
  puzzles.forEach((puzzle, idx) => {
    if (solY > dims.height - 1.2) {
      doc.addPage([dims.width, dims.height], 'portrait');
      solY = marginT + 0.5;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`#${idx + 1}: ${puzzle.authorOrSource}`, marginL, solY);
    solY += 0.22;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    const splitOrig = doc.splitTextToSize(`"${puzzle.originalText}"`, contentW);
    doc.text(splitOrig, marginL, solY);
    solY += splitOrig.length * 0.2 + 0.25;
  });

  doc.save(`kdp_cryptogram_book_${batchCount}_puzzles_${trimSize}.pdf`);
}

/**
 * 5. Exports Complete Multi-Page 9x9 Sudoku Book PDF + 4-per-page Answer Keys
 */
export async function exportSudokuBookPdf(
  batchCount: number = 20,
  difficulty: SudokuDifficulty = 'medium',
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const marginB = 0.75;
  const contentW = dims.width - marginL - marginR;
  const contentH = dims.height - marginT - marginB;

  // 1. Cover / Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('THE ULTIMATE', dims.width / 2, dims.height / 2 - 1.2, { align: 'center' });
  doc.setFontSize(36);
  doc.text('SUDOKU BOOK', dims.width / 2, dims.height / 2 - 0.5, { align: 'center' });
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${batchCount} ${difficulty.toUpperCase()} Puzzles with Complete Solutions`, dims.width / 2, dims.height / 2 + 0.2, { align: 'center' });

  // Generate Sudokus
  const puzzles = Array.from({ length: batchCount }, () => generateSudoku(difficulty));

  // 2. Puzzle Pages (1 per page)
  puzzles.forEach((p, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    // Page Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Sudoku #${idx + 1}`, marginL + contentW / 2, marginT + 0.3, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Difficulty: ${difficulty.toUpperCase()} • ${p.clueCount} Clues`, marginL + contentW / 2, marginT + 0.55, { align: 'center' });

    // Draw 9x9 Sudoku Grid
    const boardSize = Math.min(contentW - 0.5, contentH - 2.0);
    const startX = marginL + (contentW - boardSize) / 2;
    const startY = marginT + 0.9;
    const step = boardSize / 9;

    // Draw Numbers & Cells
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(trimSize === '8.5x11' ? 18 : 13);
    doc.setTextColor(15, 23, 42);

    for (let r = 0; r < 9; r++) {
      for (let c = 0; c < 9; c++) {
        const val = p.puzzleGrid[r][c];
        if (val !== null) {
          doc.text(
            val.toString(),
            startX + c * step + step / 2,
            startY + r * step + step * 0.7,
            { align: 'center' }
          );
        }
      }
    }

    // Draw Grid Lines
    for (let i = 0; i <= 9; i++) {
      const isThick = i % 3 === 0;
      doc.setDrawColor(15, 23, 42);
      doc.setLineWidth(isThick ? 0.025 : 0.008);

      // Horizontal
      doc.line(startX, startY + i * step, startX + boardSize, startY + i * step);
      // Vertical
      doc.line(startX + i * step, startY, startX + i * step, startY + boardSize);
    }

    // Page Number
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${idx + 1}`, dims.width / 2, dims.height - 0.4, { align: 'center' });
  });

  // 3. Solutions Section Header
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('SOLUTIONS', dims.width / 2, dims.height / 2, { align: 'center' });

  // 4. Solutions Grids (4 per page)
  const solutionsPerPage = 4;
  const numSolutionPages = Math.ceil(puzzles.length / solutionsPerPage);

  for (let sPage = 0; sPage < numSolutionPages; sPage++) {
    doc.addPage([dims.width, dims.height], 'portrait');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.text(`Solutions — Part ${sPage + 1}`, dims.width / 2, marginT + 0.2, { align: 'center' });

    const pagePuzzles = puzzles.slice(sPage * solutionsPerPage, (sPage + 1) * solutionsPerPage);
    const subW = (contentW - 0.4) / 2;
    const subH = (contentH - 1.0) / 2;

    pagePuzzles.forEach((p, subIdx) => {
      const col = subIdx % 2;
      const row = Math.floor(subIdx / 2);
      const bx = marginL + col * (subW + 0.4);
      const by = marginT + 0.5 + row * (subH + 0.5);

      const realIdx = sPage * solutionsPerPage + subIdx + 1;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`Sudoku #${realIdx} Solution`, bx + subW / 2, by, { align: 'center' });

      const miniSize = Math.min(subW - 0.2, subH - 0.3);
      const mStartX = bx + (subW - miniSize) / 2;
      const mStartY = by + 0.15;
      const mStep = miniSize / 9;

      // Fill Solution Numbers
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(miniSize > 3.0 ? 9 : 7);
      for (let r = 0; r < 9; r++) {
        for (let c = 0; c < 9; c++) {
          const val = p.solutionGrid[r][c];
          doc.text(
            val.toString(),
            mStartX + c * mStep + mStep / 2,
            mStartY + r * mStep + mStep * 0.75,
            { align: 'center' }
          );
        }
      }

      // Draw Grid
      for (let i = 0; i <= 9; i++) {
        const isThick = i % 3 === 0;
        doc.setDrawColor(15, 23, 42);
        doc.setLineWidth(isThick ? 0.015 : 0.005);
        doc.line(mStartX, mStartY + i * mStep, mStartX + miniSize, mStartY + i * mStep);
        doc.line(mStartX + i * mStep, mStartY, mStartX + i * mStep, mStartY + miniSize);
      }
    });
  }

  doc.save(`kdp_sudoku_book_${batchCount}_${difficulty}_${trimSize}.pdf`);
}

/**
 * 6. Exports Complete Multi-Page Clued Crossword Book PDF + Answer Keys
 */
export async function exportCrosswordBookPdf(
  batchCount: number = 10,
  theme: string = 'science',
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const marginB = 0.75;
  const contentW = dims.width - marginL - marginR;
  const contentH = dims.height - marginT - marginB;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('THE ULTIMATE', dims.width / 2, dims.height / 2 - 1.2, { align: 'center' });
  doc.setFontSize(36);
  doc.text('CROSSWORD BOOK', dims.width / 2, dims.height / 2 - 0.5, { align: 'center' });
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${batchCount} Themed Crosswords with Clues & Complete Solutions`, dims.width / 2, dims.height / 2 + 0.2, { align: 'center' });

  // Generate Crosswords
  const themesList = Object.keys(CROSSWORD_THEMES);
  const puzzles = Array.from({ length: batchCount }, (_, idx) => {
    const chosenTheme = themesList[idx % themesList.length];
    return generateCrossword(chosenTheme, 13);
  });

  // Puzzle Pages (1 per page)
  puzzles.forEach((p, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Crossword #${idx + 1}: ${p.theme}`, marginL + contentW / 2, marginT + 0.3, { align: 'center' });

    // Grid Layout (Top)
    const gridSize = Math.min(contentW, 4.5);
    const startX = marginL + (contentW - gridSize) / 2;
    const startY = marginT + 0.6;
    const step = gridSize / p.gridSize;

    // Draw Crossword Grid
    for (let r = 0; r < p.gridSize; r++) {
      for (let c = 0; c < p.gridSize; c++) {
        const cell = p.grid[r][c];
        const cx = startX + c * step;
        const cy = startY + r * step;

        if (cell.isBlocked) {
          doc.setFillColor(15, 23, 42);
          doc.rect(cx, cy, step, step, 'F');
        } else {
          doc.setFillColor(255, 255, 255);
          doc.rect(cx, cy, step, step, 'F');
          doc.setDrawColor(15, 23, 42);
          doc.setLineWidth(0.008);
          doc.rect(cx, cy, step, step, 'S');

          // Number in top-left corner
          if (cell.number !== null) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(6);
            doc.setTextColor(15, 23, 42);
            doc.text(cell.number.toString(), cx + 0.03, cy + 0.08);
          }
        }
      }
    }

    // Clues Columns (Bottom)
    let clueY = startY + gridSize + 0.35;
    const colW = (contentW - 0.4) / 2;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('ACROSS', marginL, clueY);
    doc.text('DOWN', marginL + colW + 0.4, clueY);

    clueY += 0.2;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(51, 65, 85);

    // Across Clues
    let curAcrossY = clueY;
    p.acrossClues.forEach(c => {
      const line = `${c.number}. ${c.clue}`;
      const split = doc.splitTextToSize(line, colW);
      doc.text(split, marginL, curAcrossY);
      curAcrossY += split.length * 0.14 + 0.04;
    });

    // Down Clues
    let curDownY = clueY;
    p.downClues.forEach(c => {
      const line = `${c.number}. ${c.clue}`;
      const split = doc.splitTextToSize(line, colW);
      doc.text(split, marginL + colW + 0.4, curDownY);
      curDownY += split.length * 0.14 + 0.04;
    });

    // Page number
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${idx + 1}`, dims.width / 2, dims.height - 0.4, { align: 'center' });
  });

  // Solutions Section
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.text('SOLUTIONS', dims.width / 2, dims.height / 2, { align: 'center' });

  puzzles.forEach((p, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(`Solution #${idx + 1}: ${p.theme}`, dims.width / 2, marginT + 0.3, { align: 'center' });

    const gridSize = Math.min(contentW, 5.0);
    const startX = marginL + (contentW - gridSize) / 2;
    const startY = marginT + 0.7;
    const step = gridSize / p.gridSize;

    for (let r = 0; r < p.gridSize; r++) {
      for (let c = 0; c < p.gridSize; c++) {
        const cell = p.grid[r][c];
        const cx = startX + c * step;
        const cy = startY + r * step;

        if (cell.isBlocked) {
          doc.setFillColor(15, 23, 42);
          doc.rect(cx, cy, step, step, 'F');
        } else {
          doc.setFillColor(255, 255, 255);
          doc.rect(cx, cy, step, step, 'F');
          doc.setDrawColor(15, 23, 42);
          doc.setLineWidth(0.008);
          doc.rect(cx, cy, step, step, 'S');

          // Letter
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(10);
          doc.setTextColor(16, 185, 129); // emerald green
          doc.text(cell.letter, cx + step / 2, cy + step * 0.7, { align: 'center' });
        }
      }
    }
  });

  doc.save(`kdp_crossword_book_${batchCount}_puzzles_${trimSize}.pdf`);
}

/**
 * 7. Exports 300 DPI Children's Illustrated Picture Book PDF
 */
export async function exportChildrensBookPdf(
  project: ChildrensBookProject,
  trimSize: string = '8.5x8.5'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x8.5'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const contentW = dims.width - marginL - marginR;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text(project.title.toUpperCase(), dims.width / 2, dims.height / 2 - 0.8, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`An Illustrated Story for Ages ${project.targetAge}`, dims.width / 2, dims.height / 2 - 0.2, { align: 'center' });

  doc.setFontSize(11);
  doc.text(`Art Style: ${project.character.artStyle}`, dims.width / 2, dims.height / 2 + 0.3, { align: 'center' });

  // Story Spreads (Left text page, Right illustration placeholder / visual page)
  project.spreads.forEach((spread) => {
    // Left Page (Story Prose)
    doc.addPage([dims.width, dims.height], 'portrait');
    doc.setFont('times', 'normal');
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42);

    const splitText = doc.splitTextToSize(spread.storyText, contentW - 0.4);
    const textY = (dims.height - splitText.length * 0.35) / 2;
    doc.text(splitText, marginL + (contentW - 0.4) / 2, textY, { align: 'center', lineHeightFactor: 1.5 });

    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${spread.leftPageNumber}`, dims.width / 2, dims.height - 0.4, { align: 'center' });

    // Right Page (Illustration Scene Frame)
    doc.addPage([dims.width, dims.height], 'portrait');
    
    // Decorative Frame for illustration
    const frameSize = dims.width - 1.2;
    const fX = 0.6;
    const fY = (dims.height - frameSize) / 2 - 0.2;

    doc.setDrawColor(203, 213, 225);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(fX, fY, frameSize, frameSize, 0.1, 0.1, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139);
    doc.text(`[ Illustration: Spread ${spread.spreadNumber} ]`, dims.width / 2, fY + frameSize / 2 - 0.4, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    const splitScene = doc.splitTextToSize(spread.sceneDescription, frameSize - 0.6);
    doc.text(splitScene, dims.width / 2, fY + frameSize / 2, { align: 'center' });

    doc.text(`Page ${spread.rightPageNumber}`, dims.width / 2, dims.height - 0.4, { align: 'center' });
  });

  doc.save(`kdp_childrens_book_${project.id}_${trimSize}.pdf`);
}

/**
 * 8. Exports 300 DPI Luxury Cookbook Manuscript PDF
 */
export async function exportCookbookPdf(
  project: CookbookProject,
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const contentW = dims.width - marginL - marginR;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(32);
  doc.setTextColor(15, 23, 42);
  doc.text(project.bookTitle.toUpperCase(), dims.width / 2, dims.height / 2 - 0.8, { align: 'center' });

  doc.setFontSize(16);
  doc.setFont('times', 'italic');
  doc.setTextColor(100, 116, 139);
  doc.text(project.theme, dims.width / 2, dims.height / 2 - 0.2, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`By ${project.authorName}`, dims.width / 2, dims.height / 2 + 0.4, { align: 'center' });

  // Recipe Pages (1 recipe per page)
  project.recipes.forEach((rec, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    // Header
    let y = marginT + 0.2;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(147, 51, 234); // purple-600
    doc.text(rec.category.toUpperCase(), marginL, y);

    y += 0.35;
    doc.setFont('times', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42);
    doc.text(rec.title, marginL, y);

    y += 0.25;
    doc.setFont('times', 'italic');
    doc.setFontSize(10.5);
    doc.setTextColor(71, 85, 105);
    const splitSub = doc.splitTextToSize(rec.subtitle, contentW);
    doc.text(splitSub, marginL, y);

    // Meta Specs Bar (Prep time, Cook time, Servings, Calories)
    y += splitSub.length * 0.18 + 0.2;
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(marginL, y, contentW, 0.45, 0.05, 0.05, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text(`Prep: ${rec.prepTimeMinutes} mins  |  Cook: ${rec.cookTimeMinutes} mins  |  Servings: ${rec.servings}  |  Calories: ${rec.nutrition.calories} kcal`, marginL + 0.2, y + 0.28);

    // 2-Column Section: Ingredients (Left) vs Instructions (Right)
    y += 0.75;
    const colLeftW = contentW * 0.38;
    const colRightW = contentW * 0.58;
    const colRightX = marginL + colLeftW + 0.3;

    // Left Column: Ingredients
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('INGREDIENTS', marginL, y);

    let ingY = y + 0.25;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);

    rec.ingredients.forEach((ing) => {
      const line = `• ${ing.amount} ${ing.item}${ing.notes ? ` (${ing.notes})` : ''}`;
      const splitIng = doc.splitTextToSize(line, colLeftW);
      doc.text(splitIng, marginL, ingY);
      ingY += splitIng.length * 0.16 + 0.04;
    });

    // Right Column: Instructions
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('INSTRUCTIONS', colRightX, y);

    let instY = y + 0.25;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);

    rec.instructions.forEach((step, sIdx) => {
      const line = `${sIdx + 1}. ${step}`;
      const splitStep = doc.splitTextToSize(line, colRightW);
      doc.text(splitStep, colRightX, instY);
      instY += splitStep.length * 0.16 + 0.08;
    });

    // Chef's Pro Tip Box at bottom
    const boxY = Math.max(ingY, instY) + 0.3;
    if (boxY < dims.height - 1.2) {
      doc.setFillColor(254, 243, 199); // amber-50
      doc.setDrawColor(251, 191, 36);
      doc.roundedRect(marginL, boxY, contentW, 0.6, 0.05, 0.05, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(146, 64, 14);
      doc.text('CHEF\'S PRO TIP:', marginL + 0.15, boxY + 0.22);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      const splitTip = doc.splitTextToSize(rec.chefTip, contentW - 0.3);
      doc.text(splitTip, marginL + 0.15, boxY + 0.42);
    }

    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${idx + 1}`, dims.width / 2, dims.height - 0.4, { align: 'center' });
  });

  doc.save(`kdp_cookbook_${project.id}_${trimSize}.pdf`);
}

/**
 * 9. Exports Multi-Page Low-Content Planner / Journal Interior PDF
 */
export async function exportPlannerBookPdf(config: PlannerConfig): Promise<void> {
  const dims = TRIM_SIZES_INCHES[config.trimSize] || TRIM_SIZES_INCHES['6x9'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  // Belongs to Page (Cover Page)
  doc.setFont('times', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(15, 23, 42);
  doc.text(config.title.toUpperCase(), dims.width / 2, dims.height / 2 - 1.0, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('THIS PLANNER BELONGS TO:', dims.width / 2, dims.height / 2 - 0.2, { align: 'center' });

  doc.setDrawColor(148, 163, 184);
  doc.line(dims.width / 2 - 1.5, dims.height / 2 + 0.4, dims.width / 2 + 1.5, dims.height / 2 + 0.4);

  // Generate N Repeating Interior Pages with Mirrored Gutter Margins (0.75" inside spine, 0.5" outside)
  for (let p = 1; p <= config.pageCount; p++) {
    doc.addPage([dims.width, dims.height], 'portrait');
    const isOdd = p % 2 !== 0;
    const marginL = isOdd ? 0.75 : 0.5; // Left gutter for odd, right gutter for even
    const marginR = isOdd ? 0.5 : 0.75;
    const marginT = 0.65;
    const contentW = dims.width - marginL - marginR;

    if (config.type === 'daily-productivity') {
      // Header: Date & Day
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(15, 23, 42);
      doc.text('DAILY PRODUCTIVITY PLANNER', marginL, marginT + 0.2);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      doc.text('Date: ______________  |  Day: M  T  W  T  F  S  S', marginL, marginT + 0.45);

      // Top 3 Priorities Box
      let y = marginT + 0.75;
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(marginL, y, contentW, 1.1, 0.05, 0.05, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text('TOP 3 PRIORITIES FOR TODAY', marginL + 0.15, y + 0.25);

      for (let i = 1; i <= 3; i++) {
        doc.rect(marginL + 0.15, y + 0.28 + i * 0.22, 0.12, 0.12);
        doc.setDrawColor(203, 213, 225);
        doc.line(marginL + 0.35, y + 0.38 + i * 0.22, marginL + contentW - 0.2, y + 0.38 + i * 0.22);
      }

      // Schedule (Left) vs To-Do (Right)
      y += 1.35;
      const colW = (contentW - 0.3) / 2;

      // Hourly Schedule (6am - 8pm)
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('HOURLY SCHEDULE', marginL, y);

      const hours = ['6 AM', '7 AM', '8 AM', '9 AM', '10 AM', '11 AM', '12 PM', '1 PM', '2 PM', '3 PM', '4 PM', '5 PM', '6 PM', '7 PM', '8 PM'];
      hours.forEach((h, hIdx) => {
        const lineY = y + 0.22 + hIdx * 0.24;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text(h, marginL, lineY);
        doc.setDrawColor(226, 232, 240);
        doc.line(marginL + 0.45, lineY, marginL + colW, lineY);
      });

      // To-Do Checklists (Right)
      const rightX = marginL + colW + 0.3;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text('TO-DO CHECKLIST', rightX, y);

      for (let t = 0; t < 12; t++) {
        const lineY = y + 0.22 + t * 0.24;
        doc.rect(rightX, lineY - 0.08, 0.1, 0.1);
        doc.setDrawColor(226, 232, 240);
        doc.line(rightX + 0.2, lineY, rightX + colW, lineY);
      }

      // Water Tracker at bottom
      const botY = dims.height - 1.2;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(15, 23, 42);
      doc.text('WATER TRACKER:  ○ ○ ○ ○ ○ ○ ○ ○ (8 Glasses)', marginL, botY);
    } 
    else if (config.type === 'dot-grid') {
      // 5mm Bullet Dot Grid
      const step = 0.19685; // 5mm in inches
      doc.setFillColor(148, 163, 184);

      for (let dx = marginL; dx <= marginL + contentW; dx += step) {
        for (let dy = marginT; dy <= dims.height - marginT; dy += step) {
          doc.circle(dx, dy, 0.006, 'F');
        }
      }
    } 
    else {
      // Lined Journal / Ruled Notebook
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text('DATE: _______________', marginL, marginT + 0.2);

      const lineStep = 0.3; // standard line spacing
      doc.setDrawColor(203, 213, 225);
      for (let ly = marginT + 0.6; ly <= dims.height - 0.8; ly += lineStep) {
        doc.line(marginL, ly, marginL + contentW, ly);
      }
    }

    // Page Number
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`${p}`, isOdd ? marginL + contentW - 0.1 : marginL + 0.1, dims.height - 0.35);
  }

  doc.save(`kdp_planner_${config.type}_${config.pageCount}p_${config.trimSize}.pdf`);
}

/**
 * 10. Exports 300 DPI Non-Fiction & Business Blueprint Manuscript PDF
 */
export async function exportNonFictionBookPdf(
  project: NonFictionProject,
  trimSize: string = '6x9'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['6x9'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const contentW = dims.width - marginL - marginR;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(26);
  doc.setTextColor(15, 23, 42);
  doc.text(project.title.toUpperCase(), dims.width / 2, dims.height / 2 - 0.8, { align: 'center' });

  doc.setFontSize(13);
  doc.setFont('times', 'italic');
  doc.setTextColor(100, 116, 139);
  const splitSub = doc.splitTextToSize(project.subtitle, contentW);
  doc.text(splitSub, dims.width / 2, dims.height / 2 - 0.1, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`By ${project.authorName}`, dims.width / 2, dims.height / 2 + 0.6, { align: 'center' });

  // Chapters
  project.chapters.forEach((chap) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    let y = marginT + 0.2;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(79, 70, 229); // indigo-600
    doc.text(`CHAPTER ${chap.chapterNumber}`, marginL, y);

    y += 0.3;
    doc.setFont('times', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(15, 23, 42);
    doc.text(chap.title, marginL, y);

    y += 0.22;
    doc.setFont('times', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(chap.subtitle, marginL, y);

    // Chapter Hook Box
    y += 0.35;
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(marginL, y, contentW, 0.8, 0.05, 0.05, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    doc.text('THE CORE THESIS:', marginL + 0.15, y + 0.2);

    doc.setFont('times', 'italic');
    doc.setFontSize(9);
    const splitHook = doc.splitTextToSize(`"${chap.hook}"`, contentW - 0.3);
    doc.text(splitHook, marginL + 0.15, y + 0.38);

    // Framework Section
    y += 1.05;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(chap.frameworkName.toUpperCase(), marginL, y);

    y += 0.22;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    chap.frameworkSteps.forEach((step, sIdx) => {
      const splitStep = doc.splitTextToSize(`${sIdx + 1}. ${step}`, contentW);
      doc.text(splitStep, marginL, y);
      y += splitStep.length * 0.16 + 0.06;
    });

    // Key Takeaways Box
    y += 0.15;
    doc.setFillColor(238, 242, 255); // indigo-50
    doc.setDrawColor(199, 210, 254);
    doc.roundedRect(marginL, y, contentW, 1.1, 0.05, 0.05, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(67, 56, 202);
    doc.text('KEY CHAPTER TAKEAWAYS:', marginL + 0.15, y + 0.2);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(30, 41, 59);
    let tkY = y + 0.38;
    chap.keyTakeaways.forEach((t) => {
      const splitT = doc.splitTextToSize(`• ${t}`, contentW - 0.3);
      doc.text(splitT, marginL + 0.15, tkY);
      tkY += splitT.length * 0.14 + 0.04;
    });

    // Action Checklist
    y += 1.3;
    if (y < dims.height - 1.2) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(15, 23, 42);
      doc.text('ACTION IMPLEMENTATION CHECKLIST:', marginL, y);

      y += 0.2;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(51, 65, 85);
      chap.actionChecklist.forEach((action) => {
        doc.rect(marginL, y - 0.07, 0.09, 0.09);
        const splitA = doc.splitTextToSize(action, contentW - 0.2);
        doc.text(splitA, marginL + 0.16, y);
        y += splitA.length * 0.14 + 0.06;
      });
    }

    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Chapter ${chap.chapterNumber}`, dims.width / 2, dims.height - 0.35, { align: 'center' });
  });

  doc.save(`kdp_nonfiction_${project.id}_${trimSize}.pdf`);
}

/**
 * 11. Exports 300 DPI Fiction Story Bible & Save-the-Cat Beat Sheet PDF
 */
export async function exportFictionBeatSheetPdf(
  project: FictionProject,
  trimSize: string = '6x9'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['6x9'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const contentW = dims.width - marginL - marginR;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(26);
  doc.setTextColor(15, 23, 42);
  doc.text(project.title.toUpperCase(), dims.width / 2, dims.height / 2 - 0.8, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('times', 'italic');
  doc.setTextColor(100, 116, 139);
  doc.text(`Story Bible & 15-Beat Novel Architecture`, dims.width / 2, dims.height / 2 - 0.2, { align: 'center' });

  doc.setFontSize(10.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`Genre: ${project.genre}  |  Author: ${project.authorName}`, dims.width / 2, dims.height / 2 + 0.3, { align: 'center' });

  // Character Profiles Page
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text('CHARACTER ARC & CONFLICT MATRIX', marginL, marginT + 0.3);

  let charY = marginT + 0.65;
  project.characters.forEach((char) => {
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(marginL, charY, contentW, 1.8, 0.05, 0.05, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(`${char.name} (${char.role})`, marginL + 0.15, charY + 0.25);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(185, 28, 28);
    doc.text('INTERNAL FLAW (The Lie):', marginL + 0.15, charY + 0.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(doc.splitTextToSize(char.internalFlaw, contentW - 0.3), marginL + 0.15, charY + 0.65);

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(3, 105, 161);
    doc.text('EXTERNAL WANT (Plot Goal):', marginL + 0.15, charY + 0.95);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(doc.splitTextToSize(char.externalWant, contentW - 0.3), marginL + 0.15, charY + 1.1);

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(4, 120, 87);
    doc.text('SOUL NEED (True Healing):', marginL + 0.15, charY + 1.4);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(doc.splitTextToSize(char.soulNeed, contentW - 0.3), marginL + 0.15, charY + 1.55);

    charY += 2.0;
  });

  // Story Beats (2-3 beats per page)
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text('15-BEAT NOVEL OUTLINE', marginL, marginT + 0.3);

  let beatY = marginT + 0.7;
  project.beats.forEach((beat) => {
    if (beatY > dims.height - 1.8) {
      doc.addPage([dims.width, dims.height], 'portrait');
      beatY = marginT + 0.4;
    }

    doc.setFillColor(241, 245, 249);
    doc.roundedRect(marginL, beatY, contentW, 1.2, 0.05, 0.05, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`${beat.beatName}  [${beat.targetPercentage}]`, marginL + 0.15, beatY + 0.25);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(beat.description, marginL + 0.15, beatY + 0.42);

    doc.setFont('times', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    const splitScene = doc.splitTextToSize(`Scene: ${beat.sceneSummary}`, contentW - 0.3);
    doc.text(splitScene, marginL + 0.15, beatY + 0.65);

    beatY += 1.35;
  });

  doc.save(`kdp_fiction_beat_sheet_${project.id}_${trimSize}.pdf`);
}

/**
 * 12. Exports 300 DPI Interactive Workbook PDF
 */
export async function exportWorkbookPdf(
  project: WorkbookProject,
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const contentW = dims.width - marginL - marginR;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(30);
  doc.setTextColor(15, 23, 42);
  doc.text(project.title.toUpperCase(), dims.width / 2, dims.height / 2 - 0.8, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('times', 'italic');
  doc.setTextColor(100, 116, 139);
  doc.text(project.subtitle, dims.width / 2, dims.height / 2 - 0.1, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`By ${project.authorName}`, dims.width / 2, dims.height / 2 + 0.5, { align: 'center' });

  // Workbook Sections
  project.sections.forEach((sec) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    let y = marginT + 0.2;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(14, 165, 233); // sky-500
    doc.text(`SECTION ${sec.sectionNumber}`, marginL, y);

    y += 0.35;
    doc.setFont('times', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42);
    doc.text(sec.title, marginL, y);

    y += 0.25;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Objective: ${sec.learningObjective}`, marginL, y);

    // 1. Likert Self-Assessment
    y += 0.5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('EXERCISE 1: SELF-ASSESSMENT MATRIX', marginL, y);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('(Rate 1 = Strongly Disagree to 5 = Strongly Agree)', marginL + 3.0, y);

    y += 0.3;
    sec.assessments.forEach((a) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(30, 41, 59);
      const splitSt = doc.splitTextToSize(`• ${a.statement}`, contentW - 1.8);
      doc.text(splitSt, marginL, y);

      // 1-5 Circles
      const circleStartX = marginL + contentW - 1.6;
      for (let c = 1; c <= 5; c++) {
        doc.circle(circleStartX + (c - 1) * 0.3, y - 0.03, 0.08);
        doc.setFontSize(7);
        doc.text(c.toString(), circleStartX + (c - 1) * 0.3, y, { align: 'center' });
      }

      y += splitSt.length * 0.16 + 0.12;
    });

    // 2. Guided Reflection Prompts
    y += 0.3;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('EXERCISE 2: DEEP REFLECTION WORKSHEET', marginL, y);

    y += 0.25;
    sec.reflections.forEach((r) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(r.promptQuestion, marginL, y);

      if (r.subHint) {
        y += 0.16;
        doc.setFont('times', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text(r.subHint, marginL, y);
      }

      y += 0.25;
      doc.setDrawColor(203, 213, 225);
      for (let l = 0; l < r.lineCount; l++) {
        doc.line(marginL, y + l * 0.24, marginL + contentW, y + l * 0.24);
      }
      y += r.lineCount * 0.24 + 0.2;
    });

    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${sec.sectionNumber}`, dims.width / 2, dims.height - 0.4, { align: 'center' });
  });

  doc.save(`kdp_workbook_${project.id}_${trimSize}.pdf`);
}



