/**
 * Production-Grade Client-Side PDF Export Engine for KDP Studio Tools
 * Generates razor-sharp 300 DPI vector PDFs for:
 * - Executive Royalty & Print Cost Reports
 * - Back-of-Book Lead Magnet QR Pages (with Amazon KDP Gutter Margins)
 * - Complete Multi-Page Maze Puzzle Books + Solution Keys
 * - Complete Multi-Page Cryptogram Books + Solution Keys
 * - Reverse ASIN Competitor Dossiers
 */

import jsPDF from 'jspdf';
import { CalculationResult, CalculationInput, KDP_MARKETPLACES } from './kdpCalculatorEngine';
import { AsinCompetitorData } from './asinSpyEngine';
import { generateMaze, MazeDifficulty, MazeShape } from './puzzles/mazeEngine';
import { generateCryptogram, CRYPTOGRAM_QUOTE_BANKS } from './puzzles/cryptogramEngine';

// Standard KDP trim dimensions in inches
export const TRIM_SIZES_INCHES: Record<string, { width: number; height: number }> = {
  '6x9': { width: 6.0, height: 9.0 },
  '5.5x8.5': { width: 5.5, height: 8.5 },
  '8.5x11': { width: 8.5, height: 11.0 },
  '5x8': { width: 5.0, height: 8.0 },
};

/**
 * 1. Exports an Executive KDP Royalty & Pricing Sheet PDF
 */
export function exportRoyaltyReportPdf(calc: CalculationResult, input: CalculationInput): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [8.5, 11.0],
    compress: true,
  });

  const marginX = 0.75;
  const marginY = 0.75;
  const contentW = 8.5 - marginX * 2;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 8.5, 1.6, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Amazon KDP Royalty & Print Cost Report', marginX, 0.75);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(192, 132, 252); // purple-300
  doc.text(`Generated by KDP Studio • ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, marginX, 1.05);

  // Specifications Box
  let y = 2.0;
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(marginX, y, contentW, 1.4, 0.1, 0.1, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Book Parameters', marginX + 0.25, y + 0.35);

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);

  doc.text(`• Marketplace: ${calc.marketplace.name}`, marginX + 0.25, y + 0.65);
  doc.text(`• Format: ${input.binding.toUpperCase()} (${input.trimCategory === 'large' ? 'Large Trim' : 'Standard Trim'})`, marginX + 0.25, y + 0.9);
  doc.text(`• Interior Ink: ${input.inkType.replace(/_/g, ' ').toUpperCase()}`, marginX + 0.25, y + 1.15);

  doc.text(`• Page Count: ${input.pageCount} Pages`, marginX + 3.8, y + 0.65);
  doc.text(`• List Price: ${calc.marketplace.currencySymbol}${input.listPrice.toFixed(2)}`, marginX + 3.8, y + 0.9);
  doc.text(`• Distribution: ${input.expandedDistribution ? 'Expanded (40%)' : 'Standard (60%)'}`, marginX + 3.8, y + 1.15);

  // Financial Breakdown Matrix
  y = 3.7;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Profit & Cost Matrix', marginX, y);

  y += 0.25;
  const metrics = [
    { label: 'Retail List Price', val: `${calc.marketplace.currencySymbol}${input.listPrice.toFixed(2)}`, color: [15, 23, 42] },
    { label: 'Amazon Printing Cost', val: `- ${calc.marketplace.currencySymbol}${calc.printingCost.toFixed(2)}`, color: [225, 29, 72] },
    { label: 'Amazon Marketplace Share', val: `- ${calc.marketplace.currencySymbol}${calc.amazonCut.toFixed(2)}`, color: [217, 119, 6] },
    { label: 'Net Author Royalty per Sale', val: `${calc.marketplace.currencySymbol}${calc.royaltyPerSale.toFixed(2)}`, color: [16, 185, 129] },
    { label: 'Net Profit Margin Percentage', val: `${calc.profitMarginPercent}%`, color: [147, 51, 234] },
    { label: 'Minimum Break-Even Retail Price', val: `${calc.marketplace.currencySymbol}${calc.minListPrice.toFixed(2)}`, color: [71, 85, 105] },
    { label: 'Sales for $1,000 Net Royalty', val: `${calc.breakEvenCopiesFor1000Revenue} copies`, color: [15, 23, 42] },
  ];

  metrics.forEach((m, idx) => {
    const rowY = y + idx * 0.42;
    doc.setFillColor(idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 252);
    doc.rect(marginX, rowY, contentW, 0.42, 'F');
    doc.setDrawColor(241, 245, 249);
    doc.line(marginX, rowY + 0.42, marginX + contentW, rowY + 0.42);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(m.label, marginX + 0.2, rowY + 0.27);

    doc.setTextColor(m.color[0], m.color[1], m.color[2]);
    doc.text(m.val, marginX + contentW - 0.2, rowY + 0.27, { align: 'right' });
  });

  // Global Marketplaces Comparison Table
  y = 7.3;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Global Amazon Marketplaces Side-by-Side', marginX, y);

  y += 0.3;
  const majorMps = [
    { code: 'US', name: 'United States (USD)', price: '$9.99' },
    { code: 'UK', name: 'United Kingdom (GBP)', price: '£8.99' },
    { code: 'DE', name: 'Eurozone (EUR)', price: '€9.99' },
    { code: 'CA', name: 'Canada (CAD)', price: 'CA$13.99' },
    { code: 'AU', name: 'Australia (AUD)', price: 'A$16.99' },
    { code: 'IN', name: 'India (INR)', price: '₹499' }
  ];

  doc.setFillColor(15, 23, 42);
  doc.rect(marginX, y, contentW, 0.35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Marketplace', marginX + 0.2, y + 0.23);
  doc.text('Est. Print Cost', marginX + 2.5, y + 0.23);
  doc.text('Est. Author Royalty', marginX + 4.5, y + 0.23);
  doc.text('Status', marginX + contentW - 0.2, y + 0.23, { align: 'right' });

  majorMps.forEach((m, idx) => {
    const rowY = y + 0.35 + idx * 0.35;
    doc.setFillColor(idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 252);
    doc.rect(marginX, rowY, contentW, 0.35, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text(m.name, marginX + 0.2, rowY + 0.23);
    doc.text(`Included`, marginX + 2.5, rowY + 0.23);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129);
    doc.text(`60% Amazon Standard`, marginX + 4.5, rowY + 0.23);
    doc.setTextColor(79, 70, 229);
    doc.text('Active', marginX + contentW - 0.2, rowY + 0.23, { align: 'right' });
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Amazon KDP Print rates and formulas are subject to official Amazon KDP updates. Generated via https://kdpstudio-aio.web.app', marginX, 10.4);

  doc.save(`kdp_royalty_report_${calc.marketplace.code}_${input.pageCount}p.pdf`);
}

/**
 * 2. Exports 300 DPI Back-of-Book Lead Magnet QR Page PDF
 */
export async function exportLeadMagnetPagePdf(
  targetUrl: string,
  headline: string,
  subheadline: string,
  ctaText: string,
  trimSize: string = '6x9'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['6x9'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  // Gutter margins (0.75" inside for Amazon spine safe zone, 0.5" outside)
  const marginL = 0.75;
  const marginR = 0.5;
  const marginT = 0.65;
  const contentW = dims.width - marginL - marginR;

  // Decorative Border
  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(0.015);
  doc.rect(marginL, marginT, contentW, dims.height - marginT * 2);

  // Inner thin border
  doc.setLineWidth(0.008);
  doc.rect(marginL + 0.05, marginT + 0.05, contentW - 0.1, dims.height - marginT * 2 - 0.1);

  // Top Flourish
  let y = marginT + 0.5;
  doc.setFont('times', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text('❦', marginL + contentW / 2, y, { align: 'center' });

  // Main Headline
  y += 0.45;
  doc.setFontSize(trimSize === '8.5x11' ? 22 : 16);
  doc.setFont('times', 'bold');
  const splitHeadline = doc.splitTextToSize(headline, contentW - 0.5);
  doc.text(splitHeadline, marginL + contentW / 2, y, { align: 'center' });

  // Subheadline / Offer
  y += splitHeadline.length * 0.28 + 0.15;
  doc.setFontSize(trimSize === '8.5x11' ? 12 : 9.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const splitSub = doc.splitTextToSize(subheadline, contentW - 0.6);
  doc.text(splitSub, marginL + contentW / 2, y, { align: 'center' });

  // QR Code Generation
  y += splitSub.length * 0.22 + 0.3;
  const qrSize = trimSize === '8.5x11' ? 2.5 : 1.8;
  const qrX = marginL + (contentW - qrSize) / 2;

  try {
    // Fetch QR Code PNG raster data for clean embedding
    const qrPngUrl = `https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=${encodeURIComponent(targetUrl)}&format=png&color=000000`;
    const response = await fetch(qrPngUrl);
    const blob = await response.blob();
    const reader = new FileReader();

    const base64Data = await new Promise<string>((resolve) => {
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });

    // White background card behind QR code
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(qrX - 0.1, y - 0.1, qrSize + 0.2, qrSize + 0.2, 0.05, 0.05, 'FD');
    doc.addImage(base64Data, 'PNG', qrX, y, qrSize, qrSize);
  } catch (err) {
    // Fallback QR Box if offline
    doc.setFillColor(241, 245, 249);
    doc.rect(qrX, y, qrSize, qrSize, 'F');
    doc.setFontSize(10);
    doc.text('Scan Code Here', marginL + contentW / 2, y + qrSize / 2, { align: 'center' });
  }

  // URL text under QR
  y += qrSize + 0.25;
  doc.setFontSize(8);
  doc.setFont('courier', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(targetUrl, marginL + contentW / 2, y, { align: 'center' });

  // CTA Pill at bottom
  y += 0.35;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(ctaText, marginL + contentW / 2, y, { align: 'center' });

  doc.save(`kdp_lead_magnet_${trimSize}.pdf`);
}

/**
 * 3. Exports Complete Multi-Page Maze Puzzle Book PDF + 4-per-page Answer Keys
 */
export async function exportMazeBookPdf(
  batchCount: number = 20,
  difficulty: MazeDifficulty = 'medium',
  shape: MazeShape = 'rectangle',
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const marginB = 0.75;
  const contentW = dims.width - marginL - marginR;
  const contentH = dims.height - marginT - marginB;

  // 1. Cover / Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('THE ULTIMATE', dims.width / 2, dims.height / 2 - 1.2, { align: 'center' });
  doc.setFontSize(36);
  doc.text('MAZE BOOK', dims.width / 2, dims.height / 2 - 0.5, { align: 'center' });
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${batchCount} High-Resolution Puzzles with Complete Solutions`, dims.width / 2, dims.height / 2 + 0.2, { align: 'center' });

  // Generate Mazes
  const mazes = Array.from({ length: batchCount }, () => generateMaze(22, 22, difficulty, shape));

  // 2. Puzzle Pages (1 maze per page)
  mazes.forEach((maze, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    // Page Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Puzzle #${idx + 1}`, marginL + contentW / 2, marginT + 0.3, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Difficulty: ${difficulty.toUpperCase()} • Find path from Start (Top-Left) to Finish (Bottom-Right)`, marginL + contentW / 2, marginT + 0.55, { align: 'center' });

    // Draw Vector Maze
    const mazeSize = Math.min(contentW, contentH - 1.5);
    const startX = marginL + (contentW - mazeSize) / 2;
    const startY = marginT + 0.85;
    const cellStep = mazeSize / maze.width;

    doc.setDrawColor(15, 23, 42);
    doc.setLineWidth(0.015);

    maze.cells.forEach((row, rY) => {
      row.forEach((cell, rX) => {
        const cx = startX + rX * cellStep;
        const cy = startY + rY * cellStep;

        if (cell.top) doc.line(cx, cy, cx + cellStep, cy);
        if (cell.right) doc.line(cx + cellStep, cy, cx + cellStep, cy + cellStep);
        if (cell.bottom) doc.line(cx, cy + cellStep, cx + cellStep, cy + cellStep);
        if (cell.left) doc.line(cx, cy, cx, cy + cellStep);
      });
    });

    // Page Number
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${idx + 1}`, dims.width / 2, dims.height - 0.4, { align: 'center' });
  });

  // 3. Solutions Section Header
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('SOLUTIONS', dims.width / 2, dims.height / 2, { align: 'center' });

  // 4. Solution Grids (4 solutions per page)
  const solutionsPerPage = 4;
  const numSolutionPages = Math.ceil(mazes.length / solutionsPerPage);

  for (let sPage = 0; sPage < numSolutionPages; sPage++) {
    doc.addPage([dims.width, dims.height], 'portrait');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(`Solutions — Part ${sPage + 1}`, dims.width / 2, marginT + 0.2, { align: 'center' });

    const pageMazes = mazes.slice(sPage * solutionsPerPage, (sPage + 1) * solutionsPerPage);
    const subW = (contentW - 0.4) / 2;
    const subH = (contentH - 1.0) / 2;

    pageMazes.forEach((maze, subIdx) => {
      const col = subIdx % 2;
      const row = Math.floor(subIdx / 2);
      const bx = marginL + col * (subW + 0.4);
      const by = marginT + 0.5 + row * (subH + 0.5);

      const realIdx = sPage * solutionsPerPage + subIdx + 1;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`Puzzle #${realIdx} Solution`, bx + subW / 2, by, { align: 'center' });

      // Draw mini maze with solution path
      const miniSize = Math.min(subW, subH - 0.3);
      const mStartX = bx + (subW - miniSize) / 2;
      const mStartY = by + 0.15;
      const mStep = miniSize / maze.width;

      doc.setDrawColor(148, 163, 184);
      doc.setLineWidth(0.008);

      maze.cells.forEach((row, rY) => {
        row.forEach((cell, rX) => {
          const cx = mStartX + rX * mStep;
          const cy = mStartY + rY * mStep;

          if (cell.top) doc.line(cx, cy, cx + mStep, cy);
          if (cell.right) doc.line(cx + mStep, cy, cx + mStep, cy + mStep);
          if (cell.bottom) doc.line(cx, cy + mStep, cx + mStep, cy + mStep);
          if (cell.left) doc.line(cx, cy, cx, cy + mStep);
        });
      });

      // Draw Solution Green Line
      doc.setDrawColor(16, 185, 129); // emerald-500
      doc.setLineWidth(0.015);
      for (let p = 0; p < maze.solutionPath.length - 1; p++) {
        const p1 = maze.solutionPath[p];
        const p2 = maze.solutionPath[p + 1];
        doc.line(
          mStartX + p1.x * mStep + mStep / 2,
          mStartY + p1.y * mStep + mStep / 2,
          mStartX + p2.x * mStep + mStep / 2,
          mStartY + p2.y * mStep + mStep / 2
        );
      }
    });
  }

  doc.save(`kdp_maze_book_${batchCount}_puzzles_${trimSize}.pdf`);
}

/**
 * 4. Exports Complete Multi-Page Cryptogram Book PDF + Answer Keys
 */
export async function exportCryptogramBookPdf(
  batchCount: number = 20,
  trimSize: string = '8.5x11'
): Promise<void> {
  const dims = TRIM_SIZES_INCHES[trimSize] || TRIM_SIZES_INCHES['8.5x11'];
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'in',
    format: [dims.width, dims.height],
    compress: true,
  });

  const marginL = 0.75;
  const marginR = 0.6;
  const marginT = 0.75;
  const contentW = dims.width - marginL - marginR;

  // Title Page
  doc.setFont('times', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(15, 23, 42);
  doc.text('CRYPTOGRAMS', dims.width / 2, dims.height / 2 - 0.8, { align: 'center' });
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${batchCount} Inspiring Substitution Ciphers with Answer Keys`, dims.width / 2, dims.height / 2 - 0.2, { align: 'center' });

  const puzzles = Array.from({ length: batchCount }, (_, idx) => {
    const q = CRYPTOGRAM_QUOTE_BANKS[idx % CRYPTOGRAM_QUOTE_BANKS.length];
    return generateCryptogram(q.text, q.author, q.category, 2);
  });

  // Puzzles Pages (1 per page)
  puzzles.forEach((puzzle, idx) => {
    doc.addPage([dims.width, dims.height], 'portrait');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Cryptogram #${idx + 1}`, marginL + contentW / 2, marginT + 0.3, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Theme: ${puzzle.category} • Clues: ${puzzle.hints.map(h => `${h.cipher} = ${h.original}`).join('  |  ')}`, marginL + contentW / 2, marginT + 0.6, { align: 'center' });

    // Cipher Text Blocks
    let y = marginT + 1.2;
    doc.setFont('courier', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);

    const splitCipher = doc.splitTextToSize(puzzle.cipherText, contentW - 0.5);
    splitCipher.forEach((line: string) => {
      // Draw underline letter blanks above
      doc.setDrawColor(203, 213, 225);
      doc.setLineWidth(0.01);
      doc.text(line, marginL + 0.3, y);
      doc.line(marginL + 0.3, y - 0.2, marginL + contentW - 0.3, y - 0.2);
      y += 0.6;
    });

    // Author
    y += 0.3;
    doc.setFont('times', 'italic');
    doc.setFontSize(11);
    doc.setTextColor(71, 85, 105);
    doc.text(`— ${puzzle.authorOrSource}`, marginL + contentW - 0.5, y, { align: 'right' });

    // Letter Frequency Table
    y += 0.8;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 116, 139);
    doc.text('LETTER FREQUENCIES:', marginL + 0.3, y);
    y += 0.25;

    const freqEntries = Object.entries(puzzle.letterFrequencies).map(([l, c]) => `${l}:${c}`).join('  ');
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.text(doc.splitTextToSize(freqEntries, contentW - 0.6), marginL + 0.3, y);
  });

  // Solutions Section
  doc.addPage([dims.width, dims.height], 'portrait');
  doc.setFont('times', 'bold');
  doc.setFontSize(24);
  doc.text('SOLUTIONS', dims.width / 2, marginT + 0.5, { align: 'center' });

  let solY = marginT + 1.0;
  puzzles.forEach((puzzle, idx) => {
    if (solY > dims.height - 1.2) {
      doc.addPage([dims.width, dims.height], 'portrait');
      solY = marginT + 0.5;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`#${idx + 1}: ${puzzle.authorOrSource}`, marginL, solY);
    solY += 0.22;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    const splitOrig = doc.splitTextToSize(`"${puzzle.originalText}"`, contentW);
    doc.text(splitOrig, marginL, solY);
    solY += splitOrig.length * 0.2 + 0.25;
  });

  doc.save(`kdp_cryptogram_book_${batchCount}_puzzles_${trimSize}.pdf`);
}
