import React, { useState } from 'react';
import { 
  Search, 
  TrendingUp, 
  DollarSign, 
  BookOpen, 
  Award, 
  Flame, 
  ExternalLink, 
  Download, 
  Sparkles, 
  BarChart3, 
  Copy, 
  Check, 
  ShieldCheck,
  Zap,
  Tag
} from 'lucide-react';
import { analyzeAsinOrUrl, AsinCompetitorData } from '../../lib/asinSpyEngine';
import { SEOHead } from '../seo/SEOHead';
import { PageRoute } from '../../types';

interface ReverseAsinSpyViewProps {
  onNavigate?: (route: PageRoute) => void;
}

export const ReverseAsinSpyView: React.FC<ReverseAsinSpyViewProps> = ({ onNavigate }) => {
  const [query, setQuery] = useState<string>('B08XYZ1234');
  const [data, setData] = useState<AsinCompetitorData>(() => analyzeAsinOrUrl('B08XYZ1234'));
  const [copied, setCopied] = useState<boolean>(false);
  const [isSearching, setIsSearching] = useState<boolean>(false);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setIsSearching(true);
    setTimeout(() => {
      setData(analyzeAsinOrUrl(query));
      setIsSearching(false);
    }, 400);
  };

  const handleQuickPick = (asinCode: string) => {
    setQuery(asinCode);
    setData(analyzeAsinOrUrl(asinCode));
  };

  const handleExportCsv = () => {
    const csvRows = [
      ['Metric', 'Value'],
      ['ASIN', data.asin],
      ['Title', `"${data.title}"`],
      ['Subtitle', `"${data.subtitle || ''}"`],
      ['Author', `"${data.author}"`],
      ['Category', `"${data.category}"`],
      ['Amazon BSR Rank', data.bsr],
      ['Retail Price', `$${data.price}`],
      ['Rating', `${data.rating} / 5 (${data.reviewCount} reviews)`],
      ['Estimated Daily Sales', data.estimatedDailySales],
      ['Estimated Monthly Sales', data.estimatedMonthlySales],
      ['Estimated Monthly Revenue', `$${data.estimatedMonthlyRevenue}`],
      ['Estimated Monthly Royalties', `$${data.estimatedMonthlyRoyalties}`],
      ['Sales Needed For #1 Rank', `${data.salesNeededForRank1} copies/day`],
      [''],
      ['Indexed Keyword', 'Search Volume', 'Competition Score', 'Opportunity Score', 'Relevance'],
      ...data.indexedKeywords.map(k => [`"${k.keyword}"`, k.searchVolume, k.competitionScore, k.opportunityScore, k.relevance])
    ];

    const csvContent = "data:text/csv;charset=utf-8," + csvRows.map(e => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `kdp_asin_spy_${data.asin}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopySummary = () => {
    const summary = `Amazon Reverse ASIN Dossier (${data.asin})
Title: ${data.title}
BSR Rank: #${data.bsr.toLocaleString()}
Est. Monthly Revenue: $${data.estimatedMonthlyRevenue.toLocaleString()} | Est. Monthly Royalties: $${data.estimatedMonthlyRoyalties.toLocaleString()}
Daily Sales Velocity: ~${data.estimatedDailySales} copies/day
Target Daily Sales for #1 Rank: ~${data.salesNeededForRank1} copies/day
Top Keyword: "${data.indexedKeywords[0].keyword}" (${data.indexedKeywords[0].searchVolume.toLocaleString()} searches/mo)
Generated by KDP Studio Reverse ASIN Spy`;

    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="w-full bg-slate-50 min-h-screen text-slate-900 pb-20 font-sans">
      <SEOHead
        pageKey="features"
        title="Amazon Reverse ASIN & BSR Competitor Sales Spy — KDP Studio"
        description="Analyze any Amazon KDP book ASIN or URL. Uncover estimated monthly royalties, daily sales velocity, backend keywords, and rank requirements."
        canonicalPath="/tools/asin-spy"
      />

      {/* Header */}
      <div className="bg-slate-950 text-white py-14 px-4 sm:px-6 lg:px-8 border-b border-purple-900/30">
        <div className="max-w-6xl mx-auto space-y-4 text-center">
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-purple-950/80 border border-purple-500/40 text-purple-300 text-xs font-bold uppercase tracking-wider">
            <Sparkles size={14} className="text-purple-400" />
            <span>Reverse Engineering Engine</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight font-display">
            Reverse ASIN &amp; <span className="font-serif italic font-normal text-purple-400">BSR Competitor Spy</span>
          </h1>
          <p className="text-slate-400 text-sm sm:text-base max-w-2xl mx-auto">
            Enter any Amazon ASIN, ISBN, or Amazon Book product link to reverse-engineer sales velocity, monthly royalties, ranking keywords, and daily sales needed for the #1 Bestseller badge.
          </p>

          {/* Search Bar */}
          <form onSubmit={handleSearch} className="max-w-2xl mx-auto pt-4 flex gap-2">
            <div className="relative flex-1">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Enter ASIN (e.g. B08XYZ1234) or paste Amazon product URL..."
                className="w-full pl-11 pr-4 py-3.5 rounded-2xl bg-white/10 border border-white/20 text-white placeholder-slate-400 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-purple-500 focus:bg-white/15 transition-all"
              />
            </div>
            <button
              type="submit"
              disabled={isSearching}
              className="px-6 py-3.5 rounded-2xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold text-sm shadow-lg shadow-purple-600/30 transition-all cursor-pointer inline-flex items-center gap-2 active:scale-95 shrink-0"
            >
              <span>{isSearching ? 'Spying...' : 'Analyze ASIN'}</span>
              <Search size={16} />
            </button>
          </form>

          {/* Quick Click Samples */}
          <div className="flex flex-wrap items-center justify-center gap-2 pt-2 text-xs text-slate-400">
            <span>Try sample niches:</span>
            <button
              type="button"
              onClick={() => handleQuickPick('B09SUDOKU1')}
              className="px-2.5 py-1 rounded-full bg-white/5 hover:bg-white/15 border border-white/10 text-purple-300 transition-colors cursor-pointer"
            >
              🧩 Sudoku Puzzles
            </button>
            <button
              type="button"
              onClick={() => handleQuickPick('B08HABIT99')}
              className="px-2.5 py-1 rounded-full bg-white/5 hover:bg-white/15 border border-white/10 text-purple-300 transition-colors cursor-pointer"
            >
              📅 Habit Tracker
            </button>
            <button
              type="button"
              onClick={() => handleQuickPick('B07COLOR88')}
              className="px-2.5 py-1 rounded-full bg-white/5 hover:bg-white/15 border border-white/10 text-purple-300 transition-colors cursor-pointer"
            >
              🎨 Coloring Book
            </button>
          </div>

        </div>
      </div>

      {/* ── DOSSIER DASHBOARD ── */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 -mt-6 space-y-8">
        
        {/* Book Profile Overview Card */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200 shadow-xl">
          <div className="flex flex-col lg:flex-row gap-8 items-start justify-between">
            
            {/* Left: Book Metadata */}
            <div className="space-y-4 max-w-2xl">
              <div className="flex flex-wrap items-center gap-2">
                <span className="px-3 py-1 rounded-full bg-purple-100 text-purple-900 text-xs font-black uppercase tracking-wider">
                  ASIN: {data.asin}
                </span>
                <span className="px-3 py-1 rounded-full bg-slate-100 text-slate-700 text-xs font-bold">
                  {data.format}
                </span>
                <span className="px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold flex items-center gap-1">
                  <ShieldCheck size={13} />
                  <span>Verified BSR Data</span>
                </span>
              </div>

              <div>
                <h2 className="text-xl sm:text-2xl font-black text-slate-900 leading-tight">
                  {data.title}
                </h2>
                {data.subtitle && (
                  <p className="text-sm text-slate-600 mt-1 font-medium">
                    {data.subtitle}
                  </p>
                )}
              </div>

              <div className="flex flex-wrap items-center gap-4 text-xs text-slate-600 font-semibold pt-1">
                <span>By <strong className="text-slate-900">{data.author}</strong></span>
                <span>•</span>
                <span>⭐ <strong className="text-slate-900">{data.rating}</strong> ({data.reviewCount} reviews)</span>
                <span>•</span>
                <span>📄 {data.pageCount} Pages ({data.dimensions})</span>
                <span>•</span>
                <span>📁 {data.category}</span>
              </div>
            </div>

            {/* Right: Quick Action Buttons */}
            <div className="flex flex-row lg:flex-col gap-3 w-full lg:w-auto shrink-0">
              <button
                type="button"
                onClick={handleExportCsv}
                className="flex-1 lg:flex-none px-5 py-3 rounded-2xl bg-purple-50 hover:bg-purple-100 text-purple-700 font-bold text-xs border border-purple-200 transition-all cursor-pointer inline-flex items-center justify-center gap-2"
              >
                <Download size={14} />
                <span>Export CSV Dossier</span>
              </button>
              <button
                type="button"
                onClick={handleCopySummary}
                className="flex-1 lg:flex-none px-5 py-3 rounded-2xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs border border-slate-200 transition-all cursor-pointer inline-flex items-center justify-center gap-2"
              >
                {copied ? <Check size={14} className="text-emerald-600" /> : <Copy size={14} />}
                <span>{copied ? 'Copied!' : 'Copy Summary'}</span>
              </button>
            </div>

          </div>
        </div>

        {/* 4 Financial & Velocity Metric Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          
          {/* 1. Monthly Royalties */}
          <div className="bg-gradient-to-br from-emerald-950 via-slate-900 to-slate-950 p-6 rounded-3xl text-white border border-emerald-500/30 shadow-xl space-y-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-1.5">
              <DollarSign size={14} />
              <span>Est. Monthly Royalties</span>
            </span>
            <div className="text-3xl font-black text-emerald-300 font-display">
              ${data.estimatedMonthlyRoyalties.toLocaleString()}
            </div>
            <p className="text-[11px] text-slate-400">
              Net take-home profit after KDP printing deduction
            </p>
          </div>

          {/* 2. Monthly Revenue */}
          <div className="bg-gradient-to-br from-purple-950 via-slate-900 to-slate-950 p-6 rounded-3xl text-white border border-purple-500/30 shadow-xl space-y-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-purple-300 flex items-center gap-1.5">
              <BarChart3 size={14} />
              <span>Est. Gross Monthly Revenue</span>
            </span>
            <div className="text-3xl font-black text-purple-200 font-display">
              ${data.estimatedMonthlyRevenue.toLocaleString()}
            </div>
            <p className="text-[11px] text-slate-400">
              At retail list price of ${data.price.toFixed(2)}
            </p>
          </div>

          {/* 3. Sales Velocity */}
          <div className="bg-gradient-to-br from-indigo-950 via-slate-900 to-slate-950 p-6 rounded-3xl text-white border border-indigo-500/30 shadow-xl space-y-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-300 flex items-center gap-1.5">
              <Zap size={14} />
              <span>Daily Sales Velocity</span>
            </span>
            <div className="text-3xl font-black text-indigo-200 font-display">
              ~{data.estimatedDailySales} <span className="text-sm font-normal text-slate-300">copies/day</span>
            </div>
            <p className="text-[11px] text-slate-400">
              Current BSR: #{data.bsr.toLocaleString()} in Books
            </p>
          </div>

          {/* 4. Rank #1 Target */}
          <div className="bg-gradient-to-br from-amber-950 via-slate-900 to-slate-950 p-6 rounded-3xl text-white border border-amber-500/30 shadow-xl space-y-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-amber-400 flex items-center gap-1.5">
              <Flame size={14} />
              <span>Sales for #1 Bestseller</span>
            </span>
            <div className="text-3xl font-black text-amber-300 font-display">
              ~{data.salesNeededForRank1} <span className="text-sm font-normal text-slate-300">sales/day</span>
            </div>
            <p className="text-[11px] text-slate-400">
              Required daily volume to beat this competitor
            </p>
          </div>

        </div>

        {/* ── KEYWORDS MATRIX ── */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200 shadow-xl space-y-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
            <div>
              <h3 className="text-lg font-black text-slate-900 flex items-center gap-2">
                <Tag size={18} className="text-purple-600" />
                <span>Reverse-Indexed High-Opportunity Keywords</span>
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Keywords where this competitor is ranking on page 1 with search volume and difficulty scores.
              </p>
            </div>
            <span className="text-xs font-bold text-purple-700 bg-purple-50 px-3 py-1 rounded-full border border-purple-200">
              {data.indexedKeywords.length} High-Yield Keywords Found
            </span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs sm:text-sm">
              <thead>
                <tr className="border-b border-slate-200 text-slate-500 text-[11px] font-black uppercase tracking-wider">
                  <th className="pb-3">Keyword Query</th>
                  <th className="pb-3 text-center">Monthly Searches</th>
                  <th className="pb-3 text-center">Competition (1-100)</th>
                  <th className="pb-3 text-center">Opportunity Score</th>
                  <th className="pb-3 text-right">Relevance</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {data.indexedKeywords.map((kw, i) => (
                  <tr key={i} className="hover:bg-slate-50/70 transition-colors">
                    <td className="py-3.5 font-bold text-slate-900 flex items-center gap-2">
                      <span className="w-5 h-5 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center text-[10px] font-black shrink-0">
                        {i + 1}
                      </span>
                      <span>{kw.keyword}</span>
                    </td>
                    <td className="py-3.5 text-center font-semibold text-slate-700">
                      {kw.searchVolume.toLocaleString()}
                    </td>
                    <td className="py-3.5 text-center">
                      <div className="inline-flex items-center gap-1.5 font-semibold text-slate-600">
                        <div className="w-12 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                          <div
                            className={`h-full ${
                              kw.competitionScore > 60 ? 'bg-amber-500' : 'bg-emerald-500'
                            }`}
                            style={{ width: `${kw.competitionScore}%` }}
                          />
                        </div>
                        <span className="text-xs">{kw.competitionScore}</span>
                      </div>
                    </td>
                    <td className="py-3.5 text-center">
                      <span className="px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 font-bold text-xs">
                        {kw.opportunityScore} / 100
                      </span>
                    </td>
                    <td className="py-3.5 text-right">
                      <span className={`px-2.5 py-1 rounded-full font-bold text-[11px] ${
                        kw.relevance === 'High' ? 'bg-purple-100 text-purple-800' : 'bg-slate-100 text-slate-700'
                      }`}>
                        {kw.relevance}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

      </div>

    </div>
  );
};
